In [ ]:
from os import chdir
from pathlib import Path

cwd = Path.cwd()
print(f"CWD: {cwd}")
if cwd.name == "code":
    chdir("..")
print(f"CWD: {Path.cwd()}")

In [31]:
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torch
from tqdm import tqdm
import pandas as pd
import numpy as np

In [9]:
train_df = pd.read_csv("dataset/hm_train_df.csv")
train_df.head()

   customer_id  product_code  bought
0            0             0       2
1            0             1       2
2            0             2       1
3            0             3       1
4            0             4       1

In [17]:
val_df = pd.read_csv("dataset/hm_val_df.csv")
val_df.head()

   customer_id  product_code  bought
0            0          1389       1
1            0          3240       1
2            0          2767       1
3            0           846       1
4            0           411       1

In [18]:
n_users = train_df['customer_id'].nunique()
n_items = train_df['product_code'].nunique()

In [19]:
class HMDataset(Dataset):
    def __init__(self, x):
        self.x = x.reset_index(drop=True)

    def __len__(self):
        return self.x.shape[0]

    def __getitem__(self, index):

        row = self.x.iloc[index]
        user = torch.tensor(row.customer_id)
        item = torch.tensor(row.product_code)
        target = torch.tensor([row.bought]).float()

        return user,item,target

HMDataset(train_df)[0]

(tensor(0), tensor(0), tensor([2.]))

In [20]:
TensorDataset(torch.tensor(train_df.to_numpy()))[0]

(tensor([0, 0, 2]),)

In [21]:
def get_optimizer(net):
    optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

    return optimizer

In [24]:
import torch.nn as nn
import torch.nn.functional as F


#SVD model architecture
class HMModel(nn.Module):
    def __init__(self,n_users,n_items,k=30):
        super().__init__()
        torch.manual_seed(1)

        self.user_emb = nn.Embedding(n_users, embedding_dim=k).float()
        self.article_emb = nn.Embedding(n_items, embedding_dim=k).float()
        self.user_bias = nn.Embedding(n_users, embedding_dim=1).float()
        self.article_bias = nn.Embedding(n_items, embedding_dim=1).float()


    def forward(self, inputs):
        user_index, item_index = inputs[0], inputs[1]
        u_e = self.user_emb(user_index)
        i_e = self.article_emb(item_index)
        u_b = self.user_bias(user_index)
        i_b = self.article_bias(item_index)
        x = (u_e * i_e).sum(1) + u_b + i_b

        return x

In [25]:
#Models Initialization
model_dict = {}
for x in tqdm(range(n_users)):
    model_dict["model{0}".format(x)] = HMModel(n_users,n_items)

100%|█████████████████████████████████████| 1760/1760 [00:05<00:00, 342.51it/s]

In [26]:
model_dict

{'model0': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model1': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model2': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model3': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model4': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model5': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model6': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model7': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model8': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model9': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model10': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model11': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model12': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model13': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model14': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model15': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model16': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model17': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model18': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model19': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model20': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model21': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model22': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model23': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model24': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model25': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model26': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model27': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model28': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model29': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model30': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model31': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model32': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model33': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model34': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model35': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model36': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model37': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model38': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model39': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model40': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model41': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model42': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model43': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model44': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model45': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model46': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model47': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model48': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model49': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model50': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model51': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model52': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model53': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model54': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model55': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model56': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model57': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model58': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model59': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model60': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model61': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model62': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model63': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model64': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model65': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model66': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model67': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model68': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model69': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model70': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model71': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model72': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model73': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model74': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model75': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model76': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model77': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model78': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model79': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model80': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model81': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model82': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model83': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model84': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model85': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model86': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model87': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model88': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model89': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model90': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model91': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model92': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model93': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model94': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model95': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model96': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model97': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model98': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model99': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model100': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model101': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model102': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model103': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model104': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model105': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model106': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model107': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model108': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model109': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model110': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model111': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model112': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model113': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model114': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model115': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)
   (article_bias): Embedding(8618, 1)
 ),
 'model116': HMModel(
   (user_emb): Embedding(1760, 30)
   (article_emb): Embedding(8618, 30)
   (user_bias): Embedding(1760, 1)

In [27]:
def read_data(data):
    return tuple(d for d in data[:-1]), data[-1]

In [28]:
read_data(HMDataset(train_df)[0])

((tensor(0), tensor(0)), tensor([2.]))

In [29]:
def validate(model_dict, val_loader):

    tbar = val_loader
    criterion = nn.MSELoss()
    loss_list = []
    for i in range(len(model_dict)):
        model_dict["model{0}".format(i)].eval()

    with torch.no_grad():
        for idx, data in enumerate(tbar):
            inputs, target = read_data(data)
            logits = model_dict["model{0}".format(int(inputs[0]))](inputs)
            loss = criterion(logits, target)

            loss_list.append(loss.detach().cpu().item())
        avg_loss = np.sqrt(np.mean(loss_list))

    return avg_loss

val_dataset = HMDataset(val_df)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False)

In [32]:
val_loss = []
optimizer_dict = {}
def train(model_dict, epochs):
    criterion = nn.MSELoss()
    val_map = validate(model_dict, val_loader)
    val_loss.append(val_map)
    for i in tqdm(range(n_users)):
        optimizer_dict["model{0}".format(i)] = get_optimizer(model_dict["model{0}".format(i)])

    for e in tqdm(range(epochs)):
      for i in range(len(model_dict)):
        model_dict["model{0}".format(i)].train()
      num_samples = 1387
      random_neighbors = np.random.choice(np.arange(1760), num_samples, replace=False)#Randomly select num_samples users to upload
      weights = []
      for n in random_neighbors:#Collect the partial weight of each selected user
        weights.append(len(split_train[n]))
      weights = np.array(weights) / sum(weights)
      #local training
      for neighbor in random_neighbors:#Only get the selected users' all data
        train_dataset = HMDataset(split_train[neighbor])
        train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True)

        local_epochs = 5
        for _ in range(local_epochs):
          tbar = train_loader
          for idx, data in enumerate(tbar):
              inputs, target = read_data(data)

              optimizer = optimizer_dict["model{0}".format(int(inputs[0]))]
              optimizer.zero_grad()
              logits = model_dict["model{0}".format(int(inputs[0]))](inputs)
              loss = criterion(logits, target)
              loss.backward()
              optimizer.step()
      #aggregation
      print("**Aggregation**")
      parameters = {}
      for i in range(len(random_neighbors)):
        neighbor_model = model_dict["model{0}".format(int(random_neighbors[i]))]
        for name,param in neighbor_model.named_parameters():

            if name not in parameters:
                parameters[name] = param.data * weights[i]
            else:
                parameters[name] = torch.add(parameters[name] * weights[i],param.data)

      #Update all users' paramters
      print('**Updating**')
      for i in range(len(model_dict)):
          neighbor_model = model_dict["model{0}".format(i)]
          for name,param in neighbor_model.named_parameters():

            param.data = parameters[name]

      val_map = validate(model_dict, val_loader)
      val_loss.append(val_map)
      log_text = f"Epoch {e+1}\nValidation Loss: {val_map}\n"
      print(log_text)


train(model_dict,epochs=20)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1760/1760 [00:00<00:00, 2003.70it/s]
  0%|                                                                                                                                  | 0/20 [00:00<?, ?it/s]

NameError: name 'split_train' is not defined

In [ ]:
val_loss #Evaluation